name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Build l’image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: mon-app-devops:latest
