name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2

      - name: Installer Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build image Docker
        run: docker build -t mon-app-devops .

      - name: Lister les images Docker
        run: docker images
